from-js-to-ts
Fastor1us/react-burger pull request #10
Opened 2023-09-22 14:34 UTC by Fastor1us

2023-09-22 15:22 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Не использовали ts-ignore
- Использовали any только в крайних случаях
- Использовали union типы

Необходимо исправить:
- У вас остались не типизированы два файла
![Снимок экрана 2023-09-22 в 18 20 42](https://github.com/Fastor1us/react-burger/assets/60173362/8ee767ce-28d7-41c5-808a-379d96847da5)


В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-09-22 15:22 UTC, andryxxa93 commented on src/components/burger-constructor/chosen-ingredient/chosen-ingredient.tsx
> +    hover(item: any, monitor: any) {
**Можно лучше**
Чтобы убрать отсюда any следует передать некоторые пропсы в `useDrop`

```
import { Identifier } from "dnd-core";


  const [{ handlerId }, drop] = useDrop<
    {
      ingredient: TConstructorIngredient;
      index: number;
    },
    unknown,
    { handlerId: Identifier | null }
  >
```

2023-09-22 15:22 UTC, andryxxa93 commented on src/utils/api/burger-api.ts
> +const baseQueryWithReauth = async (args: any, api: any, extraOptions: any) => {
**Можно лучше**
Тут можно типизировать следующим образом

```tsx
const baseQueryWithReauth = async (args: string | FetchArgs, api: BaseQueryApi, extraOptions: Record<string, any>) => {


export const burgerAPI = createApi({
  reducerPath: 'burgerAPI',
  baseQuery: baseQueryWithReauth,
  endpoints: build => ({
    fetchAllData: build.query({
      query: () => ({
        url: '/ingredients'
      })
    }),
    postOrderInfo: build.mutation({
      query: (arrOrderData ) => ({
        url: '/orders',
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          authorization: localStorage.getItem('accessToken')
        },
        body: JSON.stringify({
          'ingredients': arrOrderData,
        })
      }) as FetchArgs,
    }),
  })
})
```

2023-09-23 13:58 UTC, Fastor1us commented
поправил

2023-09-24 06:41 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-09-25 10:36 UTC, merged